services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: advanced-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    command: npm run start